apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vf3t2sznv-python
  janus-idp.io/tekton: vf3t2sznv-python
  backstage.io/kubernetes-id: vf3t2sznv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vf3t2sznv-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
