apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vf3t2sznv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vf3t2sznv-python 
  name: vf3t2sznv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vf3t2sznv-python 
